### ISSUE TITLE
Throws exceptions on run.

### ISSUE THREAD

**Issue by CovertJaguar** [kwilliams1987/SE-ShipSystemsManager#16]
Something seems to have broken the script. It doesn't work at all at the moment.

**Comment by kwilliams1987** [comment]
Do you have any error logs or screenshots?

**Comment by kwilliams1987** [comment]
I will try to take a look at it tonight.

**Comment by kwilliams1987** [comment]
To confirm, are you running the Visual Studio project or the compiled script in-game?

**Comment by CovertJaguar** [comment]
Compiled script in-game.

Thinking about it, if you can't duplicate it may be because I'm running ISY's Inventory Manager on the same grid and it also adds a bunch of stuff to custom data of various blocks. Perhaps the parser is broken. It was complaining about a "missing section" something or other. I'll try to get a screenshot next time I'm in game.

**Comment by kwilliams1987** [comment]
Thanks, if you can get me a little more details to work from I'll take a look.
To be honest I stopped working on this a while back but want to fix some of the bugs left over.

**Comment by CovertJaguar** [comment]
Well I don't know what to say, I tried all kinds of things to get it working before, but I loaded into a new programming block today and it worked fine.

**Comment by CovertJaguar** [comment]
That said, after I setup the zones I got a script too complex error. 🤷‍♂️

**Comment by kwilliams1987** [comment]
How many zones did you specify?

One of the things on my to do list is to convert the script to use a `yield return` state machine.

**Comment by CovertJaguar** [comment]
Maybe five zones. It wasn't that many.
